package de.biomedical_imaging.ij.clumpsplitting;

public enum SplitLineType
{
	STRAIGHTSPLITLINE, MAXIMUMINTENSITYSPLITLINE, MINIMUMINTENSITYSPLITLINE, GEODESICDISTANCESPLITLINE, MAXIMUMINTENSITYSPLITLINEFARHAN, MINIMUMINTENSITYSPLITLINEFARHAN
}
